name: Code check

on:
  pull_request:
    branches: ['*']

env:
  DATABASE_URL: 'https://fakeurl.com'
  DATABASE_AUTH_TOKEN: 'fake-token'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - run: bun run lint

  format:
    runs-on: ubuntu-latest
    name: Format

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - run: bun run format:check

  tsc:
    runs-on: ubuntu-latest
    name: Typecheck

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - run: bun run check
